// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Planner_Mealtime int32

const (
	Planner_BREAKFAST Planner_Mealtime = 0
	Planner_LUNCH     Planner_Mealtime = 1
	Planner_TEA       Planner_Mealtime = 2
	Planner_SUPPER    Planner_Mealtime = 3
	Planner_SNACK     Planner_Mealtime = 4
)

var Planner_Mealtime_name = map[int32]string{
	0: "BREAKFAST",
	1: "LUNCH",
	2: "TEA",
	3: "SUPPER",
	4: "SNACK",
}

var Planner_Mealtime_value = map[string]int32{
	"BREAKFAST": 0,
	"LUNCH":     1,
	"TEA":       2,
	"SUPPER":    3,
	"SNACK":     4,
}

func (x Planner_Mealtime) String() string {
	return proto.EnumName(Planner_Mealtime_name, int32(x))
}

func (Planner_Mealtime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{3, 0}
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLogin            int64    `protobuf:"varint,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

type Ingredient struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipeId             string   `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Measure              string   `protobuf:"bytes,4,opt,name=measure,proto3" json:"measure,omitempty"`
	Quantity             string   `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{1}
}

func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (m *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(m, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ingredient) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetMeasure() string {
	if m != nil {
		return m.Measure
	}
	return ""
}

func (m *Ingredient) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type Recipe struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string        `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Instructions         string        `protobuf:"bytes,4,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Yield                int32         `protobuf:"varint,5,opt,name=yield,proto3" json:"yield,omitempty"`
	PrepTime             int32         `protobuf:"varint,6,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	CookTime             int32         `protobuf:"varint,7,opt,name=cook_time,json=cookTime,proto3" json:"cook_time,omitempty"`
	Description          string        `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,9,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{2}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Recipe) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetInstructions() string {
	if m != nil {
		return m.Instructions
	}
	return ""
}

func (m *Recipe) GetYield() int32 {
	if m != nil {
		return m.Yield
	}
	return 0
}

func (m *Recipe) GetPrepTime() int32 {
	if m != nil {
		return m.PrepTime
	}
	return 0
}

func (m *Recipe) GetCookTime() int32 {
	if m != nil {
		return m.CookTime
	}
	return 0
}

func (m *Recipe) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Recipe) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

type Planner struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string           `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date                 int64            `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Mealtime             Planner_Mealtime `protobuf:"varint,4,opt,name=mealtime,proto3,enum=chvck.mealplanner.model.Planner_Mealtime" json:"mealtime,omitempty"`
	RecipeIds            []string         `protobuf:"bytes,5,rep,name=recipe_ids,json=recipeIds,proto3" json:"recipe_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Planner) Reset()         { *m = Planner{} }
func (m *Planner) String() string { return proto.CompactTextString(m) }
func (*Planner) ProtoMessage()    {}
func (*Planner) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{3}
}

func (m *Planner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Planner.Unmarshal(m, b)
}
func (m *Planner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Planner.Marshal(b, m, deterministic)
}
func (m *Planner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planner.Merge(m, src)
}
func (m *Planner) XXX_Size() int {
	return xxx_messageInfo_Planner.Size(m)
}
func (m *Planner) XXX_DiscardUnknown() {
	xxx_messageInfo_Planner.DiscardUnknown(m)
}

var xxx_messageInfo_Planner proto.InternalMessageInfo

func (m *Planner) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Planner) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Planner) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Planner) GetMealtime() Planner_Mealtime {
	if m != nil {
		return m.Mealtime
	}
	return Planner_BREAKFAST
}

func (m *Planner) GetRecipeIds() []string {
	if m != nil {
		return m.RecipeIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("chvck.mealplanner.model.Planner_Mealtime", Planner_Mealtime_name, Planner_Mealtime_value)
	proto.RegisterType((*User)(nil), "chvck.mealplanner.model.User")
	proto.RegisterType((*Ingredient)(nil), "chvck.mealplanner.model.Ingredient")
	proto.RegisterType((*Recipe)(nil), "chvck.mealplanner.model.Recipe")
	proto.RegisterType((*Planner)(nil), "chvck.mealplanner.model.Planner")
}

func init() { proto.RegisterFile("proto/model/model.proto", fileDescriptor_5d95f8c3a6adfa7f) }

var fileDescriptor_5d95f8c3a6adfa7f = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x9d, 0xe3, 0x38, 0x8e, 0x6e, 0xb6, 0x12, 0xc4, 0x20, 0x66, 0x63, 0x10, 0xbc, 0x97, 0xec,
	0xc5, 0x83, 0xee, 0x17, 0xa4, 0x9d, 0xc7, 0x4a, 0xbb, 0x12, 0x94, 0xe4, 0x65, 0x2f, 0xc1, 0xb3,
	0x2e, 0x9d, 0xa8, 0xbf, 0x26, 0xc9, 0x83, 0x3e, 0xef, 0x9f, 0x0c, 0xf6, 0x07, 0xf7, 0x0b, 0x86,
	0x24, 0xdb, 0xed, 0x28, 0x79, 0xe8, 0x8b, 0xd1, 0x39, 0xc7, 0x57, 0xf7, 0xdc, 0xe3, 0x6b, 0x58,
	0x34, 0xb2, 0xd6, 0xf5, 0xfb, 0xb2, 0xe6, 0x58, 0xb8, 0x67, 0x62, 0x19, 0xba, 0xc8, 0xbf, 0xff,
	0xcc, 0x6f, 0x93, 0x12, 0xb3, 0xa2, 0x29, 0xb2, 0xaa, 0x42, 0x99, 0x58, 0x39, 0xfe, 0xe3, 0xc1,
	0x78, 0xaf, 0x50, 0xd2, 0x13, 0x18, 0x09, 0x1e, 0x79, 0x4b, 0x6f, 0x45, 0xd8, 0x48, 0x70, 0xfa,
	0x0a, 0xa6, 0xad, 0x42, 0x59, 0x65, 0x25, 0x46, 0x23, 0xcb, 0x0e, 0x98, 0xbe, 0x84, 0x00, 0xcb,
	0x4c, 0x14, 0x91, 0x6f, 0x05, 0x07, 0xe8, 0x1b, 0x80, 0x5c, 0x62, 0xa6, 0x91, 0x1f, 0x32, 0x1d,
	0x8d, 0x97, 0xde, 0xca, 0x67, 0xa4, 0x63, 0xd6, 0xda, 0xc8, 0x6d, 0xc3, 0x7b, 0x39, 0x70, 0x72,
	0xc7, 0x38, 0xb9, 0xc8, 0x94, 0x3e, 0x14, 0xf5, 0x8d, 0xa8, 0xa2, 0x89, 0x93, 0x0d, 0x73, 0x65,
	0x88, 0xf8, 0x97, 0x07, 0x70, 0x51, 0xdd, 0x48, 0xe4, 0x02, 0x2b, 0xfd, 0xc8, 0xed, 0x6b, 0x20,
	0x12, 0x73, 0xd1, 0xe0, 0x41, 0xf0, 0xde, 0xae, 0x23, 0x2e, 0x38, 0xa5, 0x30, 0xb6, 0x63, 0x38,
	0xb7, 0xf6, 0x4c, 0x23, 0x08, 0x4b, 0xcc, 0x54, 0x2b, 0xd1, 0x3a, 0x25, 0xac, 0x87, 0x66, 0xf0,
	0x1f, 0x6d, 0x56, 0x69, 0xa1, 0xef, 0xac, 0x4b, 0xc2, 0x06, 0x1c, 0xff, 0x1e, 0xc1, 0x84, 0xd9,
	0x6b, 0x1f, 0x39, 0x58, 0x40, 0x68, 0xf2, 0xb9, 0xef, 0x3f, 0x31, 0xf0, 0x48, 0xf7, 0x18, 0x9e,
	0x8b, 0x4a, 0x69, 0xd9, 0xe6, 0x5a, 0xd4, 0x95, 0xea, 0x2c, 0xfc, 0xc7, 0x99, 0x90, 0xef, 0x04,
	0x16, 0xdc, 0x9a, 0x08, 0x98, 0x03, 0x66, 0xd0, 0x46, 0x62, 0x73, 0xd0, 0xa2, 0x44, 0x9b, 0x52,
	0xc0, 0xa6, 0x86, 0xd8, 0x89, 0x12, 0x8d, 0x98, 0xd7, 0xf5, 0xad, 0x13, 0x43, 0x27, 0x1a, 0xc2,
	0x8a, 0x4b, 0x98, 0x71, 0x54, 0xb9, 0x14, 0x8d, 0xb9, 0x3f, 0x9a, 0xda, 0x96, 0x0f, 0x29, 0x9a,
	0xc2, 0x4c, 0x0c, 0x11, 0xab, 0x88, 0x2c, 0xfd, 0xd5, 0xec, 0xf4, 0x6d, 0x72, 0x64, 0x75, 0x92,
	0xfb, 0xcf, 0xc1, 0x1e, 0xd6, 0xc5, 0x7f, 0x3d, 0x08, 0x37, 0xee, 0xcd, 0x27, 0xa5, 0x64, 0x36,
	0xc1, 0xa6, 0xe4, 0x33, 0x7b, 0xa6, 0x29, 0x4c, 0x4d, 0x57, 0x3b, 0x8d, 0x49, 0xe8, 0xe4, 0xf4,
	0xdd, 0x51, 0x33, 0x5d, 0xc3, 0xe4, 0x4b, 0x57, 0xc0, 0x86, 0x52, 0xb3, 0x59, 0xc3, 0x6e, 0xa8,
	0x28, 0x58, 0xfa, 0x2b, 0xc2, 0x48, 0xbf, 0x1c, 0x2a, 0xfe, 0x08, 0xd3, 0xbe, 0x88, 0xbe, 0x00,
	0x72, 0xc6, 0xd2, 0xf5, 0xe5, 0xa7, 0xf5, 0x76, 0x37, 0x7f, 0x46, 0x09, 0x04, 0x57, 0xfb, 0xeb,
	0xf3, 0xcf, 0x73, 0x8f, 0x86, 0xe0, 0xef, 0xd2, 0xf5, 0x7c, 0x44, 0x01, 0x26, 0xdb, 0xfd, 0x66,
	0x93, 0xb2, 0xb9, 0x6f, 0xf4, 0xed, 0xf5, 0xfa, 0xfc, 0x72, 0x3e, 0x3e, 0x0b, 0xbf, 0x06, 0xd6,
	0xc8, 0xb7, 0x89, 0xfd, 0xe1, 0x3e, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x09, 0xcb, 0x48,
	0x8b, 0x03, 0x00, 0x00,
}
